Repository TokTok/hs-tokstyle, pull requests merged in 2022-03, with the labels that each got.

#156 feat: Add check that all symbols used are defined.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/Callgraph.hs
  src/Tokstyle/Linter/TypeCheck.hs
  tokstyle.cabal
Labels: enhancement

#157 feat: Add cycle detection code and exemptions.
  src/Tokstyle/Linter/Callgraph.hs
Labels: enhancement

#159 cleanup: Reject paren-expr in `return`.
  src/Tokstyle/Linter/Parens.hs
Labels: cleanup

#160 feat: Check for unused symbols.
  BUILD.bazel
  src/Tokstyle/Linter/Callgraph.hs
  tokstyle.cabal
Labels: enhancement

#161 cleanup: Use type intersection instead of union for `?:`.
  src/Tokstyle/Linter/TypeCheck.hs
Labels: cleanup

#163 feat: Prevent non-pure function calls in `assert()`.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/Assert.hs
  tokstyle.cabal
Labels: enhancement

#162 chore: Add SELF_UDP_STATUS_LAN to callgraph exemption list
  src/Tokstyle/Linter/Callgraph.hs
Labels: chore

#165 fix: Consider types with the same name to be the same type.
  tools/check-c.hs
Labels: bug

#166 chore: Add more sodium functions to the list of builtins.
  src/Tokstyle/Linter/Callgraph.hs
Labels: chore

#167 fix: Consider symbols used in struct definitions as "used".
  src/Tokstyle/Linter/Callgraph.hs
  test/Tokstyle/Linter/CallgraphSpec.hs
Labels: bug

#168 docs: Add a tutorial for writing linters.
  README.md
  src/Tokstyle/Linter/CallocType.hs
  stack.yaml
  test/Tokstyle/Linter/CallocTypeSpec.hs
  test/Tokstyle/Linter/CompoundInitSpec.hs
  test/Tokstyle/LinterSpec.hs
  tokstyle.cabal
Labels: documentation

#170 fix: Fix `-Wdoc-comments` on functions with `non_null`.
  src/Tokstyle/Linter/DocComments.hs
Labels: bug

#172 fix: Fix `-Wvar-unused-in-scope` for `if` inside `for`.
  BUILD.bazel
  src/Tokstyle/Common.hs
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/BooleanReturn.hs
  src/Tokstyle/Linter/Booleans.hs
  src/Tokstyle/Linter/CallbackNames.hs
  src/Tokstyle/Linter/CallocArgs.hs
  src/Tokstyle/Linter/CallocType.hs
  src/Tokstyle/Linter/CompoundInit.hs
  src/Tokstyle/Linter/DeclsHaveDefns.hs
  src/Tokstyle/Linter/DocComments.hs
  src/Tokstyle/Linter/FuncScopes.hs
  src/Tokstyle/Linter/LargeStructParams.hs
  src/Tokstyle/Linter/LoggerConst.hs
  src/Tokstyle/Linter/MallocType.hs
  src/Tokstyle/Linter/MemcpyStructs.hs
  src/Tokstyle/Linter/NonNull.hs
  src/Tokstyle/Linter/TypeCheck.hs
  src/Tokstyle/Linter/TypedefName.hs
  src/Tokstyle/Linter/UnsafeFunc.hs
  src/Tokstyle/Linter/VarUnusedInScope.hs
  test/Tokstyle/Linter/VarUnusedInScopeSpec.hs
  tokstyle.cabal
  tools/check-c.hs
  tools/check-cimple.hs
Labels: bug

#174 feat: Output timing details for check-cimple.
  tokstyle.cabal
  tools/BUILD.bazel
  tools/check-cimple.hs
Labels: enhancement

#175 test: Add a test to make sure arrays are treated as expected.
  BUILD.bazel
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/VarUnusedInScope.hs
  test/Tokstyle/Linter/VarUnusedInScopeSpec.hs
  tokstyle.cabal
  tools/check-cimple.hs
Labels: test

#176 chore: Add cmp functions to callgraph exemptions list.
  src/Tokstyle/Linter/Callgraph.hs
Labels: chore

#178 chore: Exempt bin_pack/unpack functions from `-Wcallgraph`.
  src/Tokstyle/Linter/Callgraph.hs
Labels: chore

#179 chore: Add missing cmp function.
  src/Tokstyle/Linter/Callgraph.hs
Labels: chore

#182 chore: Add some more tox_options functions to the exemptions.
  src/Tokstyle/Linter/Callgraph.hs
Labels: chore

#180 fix: Slight improvement of pointer subtraction type check.
  src/Tokstyle/Linter/TypeCheck.hs
Labels: bug

#183 cleanup: Slightly tighten allowed implicit int conversions.
  include/msgpack
  include/msgpack.h
  include/stdint.h
  tools/check-c.hs
Labels: cleanup

#184 chore: Add tox_private.h to the exemptions list for -Wdecls-have-defns.
  src/Tokstyle/Linter/DeclsHaveDefns.hs
Labels: chore
