Repository TokTok/hs-tokstyle, pull requests merged in 2022-02, with the labels that each got.

#117 feat: Add check to make sure we don't pass large structs by value.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/LargeStructParams.hs
  tokstyle.cabal
Labels: enhancement

#119 perf: Use non-copying TraverseAst.
  src/Tokstyle/Linter/CallbackNames.hs
  src/Tokstyle/Linter/CallocArgs.hs
  src/Tokstyle/Linter/CallocType.hs
  src/Tokstyle/Linter/CompoundInit.hs
  src/Tokstyle/Linter/DeclaredOnce.hs
  src/Tokstyle/Linter/DeclsHaveDefns.hs
  src/Tokstyle/Linter/DocComments.hs
  src/Tokstyle/Linter/EnumNames.hs
  src/Tokstyle/Linter/ForLoops.hs
  src/Tokstyle/Linter/FuncPrototypes.hs
  src/Tokstyle/Linter/LargeStructParams.hs
  src/Tokstyle/Linter/LoggerCalls.hs
  src/Tokstyle/Linter/LoggerConst.hs
  src/Tokstyle/Linter/LoggerNoEscapes.hs
  src/Tokstyle/Linter/MallocType.hs
  src/Tokstyle/Linter/MemcpyStructs.hs
  src/Tokstyle/Linter/Parens.hs
  src/Tokstyle/Linter/TypeCheck.hs
  src/Tokstyle/Linter/TypedefName.hs
  src/Tokstyle/Linter/UnsafeFunc.hs
  src/Tokstyle/Linter/VarUnusedInScope.hs
  stack.yaml
  tokstyle.cabal
Labels: performance

#121 cleanup: Remove obsolete checker.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/ForLoops.hs
  tokstyle.cabal
Labels: cleanup

#122 feat: Check that all pointer arguments have nullability annotations.
  src/Tokstyle/Common.hs
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/CompoundInit.hs
  src/Tokstyle/Linter/FuncScopes.hs
  src/Tokstyle/Linter/MemcpyStructs.hs
  src/Tokstyle/Linter/MissingNonNull.hs
  src/Tokstyle/Linter/NonNull.hs
  stack.yaml
  tokstyle.cabal
Labels: enhancement

#125 chore: Use toktok-stack image for haskell stack builds.
  .github/docker/Dockerfile
Labels: chore

#123 chore: Add Packet_Direction enum to exemption list
  src/Tokstyle/Linter/LargeStructParams.hs
Labels: chore

#126 chore: Add common CI workflow, currently includes buildifier.
  .github/workflows/ci.yml
Labels: chore

#127 feat: Add type checking tool using language-c.
  include/arpa/inet.h
  include/assert.h
  include/errno.h
  include/fcntl.h
  include/limits.h
  include/math.h
  include/msgpack
  include/msgpack.h
  include/netdb.h
  include/netinet/in.h
  include/pthread.h
  include/sodium
  include/sodium.h
  include/stdarg.h
  include/stdbool.h
  include/stddef.h
  include/stdint.h
  include/stdio.h
  include/stdlib.h
  include/string.h
  include/sys/ioctl.h
  include/sys/socket.h
  include/sys/time.h
  include/sys/types.h
  include/time.h
  include/types.h
  include/unistd.h
  src/Tokstyle/Linter/CompoundInit.hs
  stack.yaml
  tokstyle.cabal
  tools/BUILD.bazel
  tools/check-c.hs
Labels: enhancement

#129 chore: Add check-c to the cabal file.
  tokstyle.cabal
Labels: chore

#130 feat: Add support for everything needed by toxav.
  include/inttypes.h
  include/opus
  include/pthread.h
  include/vpx
  tokstyle.cabal
  tools/BUILD.bazel
  tools/check-c.hs
Labels: enhancement

#131 feat: Implement stronger type checking in assignments.
  include/netinet/in.h
  include/sys/socket.h
  include/types.h
  tools/check-c.hs
Labels: enhancement

#133 cleanup: Slight improvement of this ugly code.
  tools/check-c.hs
Labels: cleanup

#134 chore: Add a new enum to the exemptions list.
  src/Tokstyle/Linter/LargeStructParams.hs
Labels: chore

#135 feat: Check boolean conversions inside logical operators.
  tools/check-c.hs
Labels: enhancement

#136 fix: Allow int-to-enum conversion.
  tools/check-c.hs
  web/webservice.hs
Labels: bug

#137 feat: Add `select()` to the libc headers.
  include/errno.h
  include/sys/select.h
  include/sys/time.h
Labels: enhancement

#139 fix: Remove exemption for binary expressions in if stmts.
  tools/check-c.hs
Labels: bug

#140 feat: Add stronger checks on casts.
  include/netdb.h
  include/stdbool.h
  include/stddef.h
  test/Tokstyle/Linter/TypeCheckSpec.hs
  tokstyle.cabal
  tools/check-c.hs
Labels: enhancement

#142 feat: Check for returning 1/0 in bool functions.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/BoolReturn.hs
  test/Tokstyle/Linter/BoolReturnSpec.hs
  tokstyle.cabal
  tools/check-c.hs
Labels: enhancement

#144 feat: Improved type checking.
  BUILD.bazel
  src/Tokstyle/Linter/TypeCheck.hs
  tokstyle.cabal
  tools/check-c.hs
  web/Tokstyle/App.hs
Labels: enhancement

#147 fix: Add `struct` to the list of types that aren't pointers.
  src/Tokstyle/Common.hs
Labels: bug

#146 feat: Add check that we don't use `sizeof(ptr)`.
  tools/check-c.hs
Labels: enhancement

#148 cleanup: Slight code improvements.
  src/Tokstyle/Linter/Constness.hs
Labels: cleanup

#149 feat: Check for comparisons of bool and non-bool.
  include/pthread.h
  tools/check-c.hs
Labels: enhancement

#150 feat: Disallow parens in assignment expressions.
  src/Tokstyle/Linter/Parens.hs
Labels: enhancement

#151 feat: Improved type checking some more.
  include/errno.h
  src/Tokstyle/Linter/TypeCheck.hs
Labels: enhancement

#152 feat: Check for `x == true` and `x == false`.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/Booleans.hs
  src/Tokstyle/Linter/TypeCheck.hs
  test/Tokstyle/Linter/BooleansSpec.hs
  tokstyle.cabal
  tools/check-cimple.hs
Labels: enhancement

#153 feat: Add check for functions that could return `bool`.
  src/Tokstyle/Linter.hs
  src/Tokstyle/Linter/BooleanReturn.hs
  src/Tokstyle/Linter/TypeCheck.hs
  test/Tokstyle/Linter/BooleanReturnSpec.hs
  tokstyle.cabal
Labels: enhancement

#155 feat: More improvements and simplifications to type check.
  src/Tokstyle/Linter/TypeCheck.hs
Labels: enhancement
